language: generic
compiler: clang
os: osx
matrix:
  include:
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: &sources
            - llvm-toolchain-precise

install:
script: make test
