language: cpp
compiler:
  - clang

dist: trusty
sudo: false

os:
  - osx
  - linux

env:
  - CXX_STDLIB=-stdlib=libc++

addons:
  apt:
    packages:
      - libc++1
      - libc++-dev

script:
  - make test CFLAGS="-O2 -coverage" CXX_STDLIB=${CXX_STDLIB}

after_success:
  - bash <(curl -s https://codecov.io/bash)
