language: generic
compiler: clang
os: osx
osx_image: xcode7.2
env: CXX=clang++ CC=clang

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++1
            - libc++-dev
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test

install:
script: make test CXX=${CXX} CC=${CC}
