language: cpp
compiler:
  - clang
  - gcc

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - clang
      - llvm-dev
      - libc++1
      - libc++-dev
    sources: &sources
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test

install:

script:
  - make test CFLAGS="-O0 -coverage" DEBUG=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
