language: cpp
compiler:
  - clang
  - gcc

dist: trusty
sudo: false

os:
  - osx
  - linux

env:
  - CXX_STDLIB=-stdlib=libstdc++
  - CXX_STDLIB=-stdlib=libc++

matrix:
   allow_failures:
     - os: linux

install:

script:
  - make test CFLAGS="-O0 -coverage" DEBUG=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
